name: release

on:
  push:
    tags:
      - v*.*.*

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: cargo build
        id: native-build
        run: cargo build --release

      - name: web-ext build
        id: ext-build
        uses: kewisch/action-web-ext@v1
        with:
          cmd: build
          source: src

      - name: web-ext sign
        id: ext-sign
        uses: kewisch/action-web-ext@v1
        with:
          cmd: sign
          source: ${{ steps.ext-build.outputs.target }}
          channel: unlisted
          apiKey: ${{ secrets.AMO_SIGN_KEY }}
          apiSecret: ${{ secrets.AMO_SIGN_SECRET }}
          timeout: 900000

      - name: release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            ${{ steps.native-build.outputs.target }}
            ${{ steps.ext-sign.outputs.target }}
